[project]
name = "nrec-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dpaulino", email = "dfpaulino@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5",
    "opencv-python>=5.0",
]

[project.scripts]
nrec-yolo = "nrec_utils.migrate_nrec_to_yolo:cli"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
    
[tool.pytest.ini_options]
testpaths = ["tests"]
